import type { Metadata } from "next";
import { Inter, Poppins, Montserrat, Recursive } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import MaxwidthWrapper from "@/components/MaxwidthWrapper";
import Rainbow from "@/components/Rainbow";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // All weights
  variable: "--font-poppins", // Define CSS variable
});
const recursive = Recursive({
  subsets: ["latin"],
});
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // All weights
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-poppins">
        <main className=" border min-h-lvh">
          <MaxwidthWrapper>
            <Rainbow />
            <Navbar />
          </MaxwidthWrapper>

          {children}
        </main>
      </body>
    </html>
  );
}
